#' @title Simple MC Water Quality Mass Balance
#'
#' @description \code{SimpleMassBalance} returns a "MassBalance" object.
#'
#' @details Use SimpleMassBalance() within ofther functions to do the mass
#'          balance stuff will use other functions to create distributions and
#'          summary bits and bobs depending on whether user wants to input full
#'          datasets or just summary stats equivalent of RQP 2.5
#'
#' @param us.q a vector of upstream quality
#' @param us.f a vector of upstream flow
#' @param dis.q a vector of discharge quality in same units as \code{us.q}
#' @param dis.f a vector of discharge flow in same units as \code{us.f}
#' @param shots number of shots in Monte Carlo runs. Numeric.
#' @param cor integer between 0 and 1 indicating correlation between flow and
#'        quality
#'
#' @return An S3 object of class "MassBalance" with the following components
#'         \itemize{
#'                  \item \code{Downstream.flow} is a vector of downstream flows
#'                  generated by individual Monte Carlo shots
#'                  \item \code{Downstream.quality} is a vector of downstream
#'                  quality generated by individual Monte Carlo shots
#'                  \item \code{Downstream.summary} vector of \code{mean} and
#'                  \code{sd} for flow and quality
#'         }
#'
#' @examples
#'      s <- 1000
#'
#'      us.flow <- rlnorm(s, meanlog = log(us.flow.mean), sdlog = log(us.flow.sd))
#'      us.qual <- rlnorm(s, meanlog = log(us.qual.mean), sdlog = log(us.qual.sd))
#'      dis.flow <- rlnorm(s, meanlog = log(dis.flow.mean), sdlog = log(dis.flow.sd))
#'      dis.qual <- rlnorm(s, meanlog = log(dis.qual.mean), sdlog = log(dis.qual.sd))
#'
#'      z <- SimpleMassBalance(us.q = us.qual, us.f = us.flow, dis.q = dis.qual,
#'      dis.f = dis.flow, shots = s, cor = 1L)
#' @export



# Define fucntions

## Use SimpleMassBalance() within ofther functions to do the mass balance stuff
## will use other functions to create distributions and summary bits and bobs
## depending on whether user wants to input full datasets or just summary stats
## equivalent of RQP 2.5
SimpleMassBalance <- function(us.q, us.f, dis.q, dis.f, shots = 2500, cor = 1L){
    stopifnot(is.numeric(us.f), is.numeric(us.q),
              is.numeric(dis.f), is.numeric(dis.q))

    l <- list(us.q = us.q, us.f = us.f, dis.q = dis.q, dis.f = dis.f)
    if (cor == 1L){
        l <- lapply(l, sort) #  perfect correaltion riv:dis flow and riv:dis qual
        ds.f <- numeric(shots)
        ds.q <- numeric(shots)
        for(i in 1:shots){
            ii <- sample(1:length(l[[1]]), 1, replace = TRUE)
            ds.f[i] <- l$us.f[ii] + l$dis.f[ii]
            ds.q[i] <- (((l$us.f[ii] * l$us.q[ii]) + (l$dis.f[ii] * l$dis.q[ii]))
                        / (l$us.f[ii] + l$dis.f[ii]))
        }
    }

    ds.stats <- data.frame(mean(ds.q), sd(ds.q), mean(ds.f), sd(ds.f))
    colnames(ds.stats) <- c("Downstream mean quality", "Downstream quality SD",
                            "Downstream mean flow", "Downstream flow SD")
    ll <- list("Downstream.flow" = ds.f, "Downstream.quality" = ds.q,
               "Downstream.summary" = ds.stats)
    class(ll) <- "MassBalance"
    ll
}


#' @title Simple MC Water Quality Mass Balance using summary statistics
#'
#' @description \code{SimpleMassBalance} returns a "MassBalance" object.
#'
#' @details use \code{SummaryMassBalance} as user input layer to access
#'          \code{SimpleMassBalance} with user inputting only summary stats for
#'          us and discharge
#'
#' @param stuff
#'
#' @return stuff
#'
#' @examples
#'          stuff <- 1
#' @export

SummaryMassBalance <- function(us.q.m, us.q.sd, us.f.m, us.f.sd, dis.q.m,
                               dis.q.sd, dis.f.m, dis.f.sd, shots = 2500,
                               cor = 1L, kSize = 10000, dist = "logNormal"){
    # first generate relevant dist
    if(dist == "logNormal"){
        us.flow <- rlnorm(kSize, meanlog = log(us.f.m), sdlog = log(us.f.sd))
        us.qual <- rlnorm(kSize, meanlog = log(us.q.m), sdlog = log(us.q.sd))
        dis.flow <- rlnorm(kSize, meanlog = log(dis.f.m), sdlog = log(dis.f.sd))
        dis.qual <- rlnorm(kSize, meanlog = log(dis.q.m), sdlog = log(dis.q.sd))
    } else if (dist == "Normal"){
        us.qual <- MCMCglmm::rtnorm(kSize, mean = us.q.m, sd = us.q.sd,
                                    lower = 0.0001)
        us.flow <- MCMCglmm::rtnorm(kSize, mean = us.f.m, sd = us.f.sd,
                                    lower = 0.0001)
        dis.qual <- MCMCglmm::rtnorm(kSize, mean = dis.q.m, sd = dis.q.sd,
                                     lower = 0.0001)
        dis.flow <- MCMCglmm::rtnorm(kSize, mean = dis.f.m, sd = dis.f.sd,
                                     lower = 0.0001)
    } else {
        stop("invalid distribution specified")
    }

    # summarise input distributions
    dis.stats <- data.frame(mean(dis.qual), sd(dis.qual), mean(dis.flow), sd(dis.flow))
    colnames(dis.stats) <- c("Discharge mean quality", "Discharge quality SD",
                             "Discharge mean flow", "Discharge flow SD")

    us.stats <- data.frame(mean(us.qual), sd(us.qual), mean(us.flow), sd(us.flow))
    colnames(us.stats) <- c("Upstream mean quality", "Upstream quality SD",
                            "Upstream mean flow", "Upstream flow SD")

    # pass distributions to SimpleMassBalance()
    z <- SimpleMassBalance(us.q = us.qual, us.f = us.flow, dis.q = dis.qual,
                           dis.f = dis.flow, shots = shots, cor = cor)

    ll <- z
    ll$Upstream.flow <- us.flow
    ll$Upstream.quality  <- us.qual
    ll$Upstream.summary <- us.stats
    ll$Discharge.flow <- dis.flow
    ll$Discharge.quality <- dis.qual
    ll$Discharge.summary <- dis.stats
    class(ll) <- "MassBalance"

    ll
}